project_id = "sznafsdzdwiwhcgrfzcb"

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-initialize]
verify_jwt = true

[functions.paystack-verify]
verify_jwt = true

[functions.submit-incident-report]
verify_jwt = false

[functions.paystack-webhook-retry]
verify_jwt = false

[functions.webhook-alerts-monitor]
verify_jwt = false

[functions.dispatch-community-alert]
verify_jwt = true

[functions.escalate-community-alerts]
verify_jwt = false

