project_id = "evsginbpruyykvwallck"

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-webhook-retry]
verify_jwt = false

[functions.webhook-alerts-monitor]
verify_jwt = false

[functions.community-sms]
verify_jwt = false


