import { useEffect, useMemo, useState, type ReactNode } from "react";
import { BellRing, Radio, ShieldAlert, Siren, Trash2, Users } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useCommunityAlertAdmin } from "@/hooks/useCommunityAlertAdmin";
import { useLanguage } from "@/hooks/useLanguage";
import { dispatchCommunityAlert, flushAlertOutbox } from "@/lib/communityAlertService";
import type { AlertChannel, AlertDraft, ContactCategory } from "@/types/communityAlert";

export default function CommunityAlerts() {
  const admin = useCommunityAlertAdmin();
  const {language,t}=useLanguage();
  const [channels,setChannels]=useState<AlertChannel[]>(["sms"]);
  const [groupIds,setGroupIds]=useState<string[]>([]);
  const [contactIds,setContactIds]=useState<string[]>([]);
  const [sending,setSending]=useState(false);
  const [draft,setDraft]=useState({incidentType:"",summary:"",location:"",threatLevel:"high",instructions:"Move to a safe location and follow responder instructions."});
  const [group,setGroup]=useState({name:"",community:"",ward:"",leader:"",escalationMinutes:15});
  const [member,setMember]=useState({groupId:"",name:"",phone:"",whatsapp:"",language:"en"});
  const [contact,setContact]=useState({name:"",category:"police" as ContactCategory,phone:"",whatsapp:"",community:"",incidentTypes:"",authorityLevel:1});
  useEffect(()=>{const flush=()=>void flushAlertOutbox().then(n=>n&&toast.success(`${n} queued alert(s) sent`));window.addEventListener("online",flush);flush();return()=>window.removeEventListener("online",flush)},[]);
  const recipients=useMemo(()=>admin.groups.filter(g=>groupIds.includes(g.id)).reduce((n,g)=>n+g.memberCount,0)+contactIds.length,[admin.groups,groupIds,contactIds]);
  const toggle=<T,>(v:T,all:T[],set:(x:T[])=>void)=>set(all.includes(v)?all.filter(x=>x!==v):[...all,v]);
  const run=async(action:()=>Promise<void>,message:string)=>{try{await action();toast.success(message)}catch(e){toast.error(e instanceof Error?e.message:"Operation failed")}};
  async function send(){if(!draft.incidentType||!draft.summary||!draft.location||!channels.length||(!groupIds.length&&!contactIds.length))return toast.error("Complete the alert and select recipients.");setSending(true);try{const payload:AlertDraft={...draft,threatLevel:draft.threatLevel as AlertDraft["threatLevel"],occurredAt:new Date().toISOString(),channels,groupIds,contactIds,language};const r=await dispatchCommunityAlert(payload);toast.success(r.queued?"Alert safely queued for delivery":`Sent: ${r.delivered}; failed: ${r.failed}`)}catch(e){toast.error(e instanceof Error?e.message:"Alert delivery failed")}finally{setSending(false)}}
  return <main className="min-h-screen bg-background p-4 md:p-8"><div className="mx-auto max-w-6xl space-y-6">
    <header><h1 className="flex items-center gap-2 text-2xl font-bold"><ShieldAlert className="text-destructive"/>{t("communityAlerts")}</h1><p className="text-sm text-muted-foreground">{t("alertSubtitle")}</p></header>
    <div className="grid gap-4 sm:grid-cols-3"><Stat icon={<Radio/>} value={admin.alerts.filter(a=>a.status==="active").length} label={t("activeIncidents")}/><Stat icon={<Users/>} value={admin.groups.length} label={t("watchGroups")}/><Stat icon={<Siren/>} value={admin.contacts.length} label={t("emergencyContacts")}/></div>
    {admin.alerts.some(a=>a.status==="active")&&<Card><CardHeader><CardTitle>{t("activeIncidents")}</CardTitle></CardHeader><CardContent className="space-y-3">{admin.alerts.filter(a=>a.status==="active").map(a=><div key={a.id} className="flex flex-col justify-between gap-3 rounded border p-3 sm:flex-row sm:items-center"><div><p className="font-semibold capitalize">{a.incident_type} · {a.threat_level}</p><p className="text-sm">{a.summary}</p><p className="text-xs text-muted-foreground">{a.location} · escalation level {a.escalation_level}</p></div><Button onClick={()=>run(()=>admin.resolveAlert(a.id),"Incident resolved")}>{t("resolved")}</Button></div>)}</CardContent></Card>}
    <Tabs defaultValue="send"><TabsList className="grid w-full grid-cols-3"><TabsTrigger value="send">{t("sendAlert")}</TabsTrigger><TabsTrigger value="groups">{t("watchGroups")}</TabsTrigger><TabsTrigger value="contacts">{t("emergencyContacts")}</TabsTrigger></TabsList>
      <TabsContent value="send"><Card><CardHeader><CardTitle className="flex items-center gap-2"><BellRing className="h-5 w-5"/>Create verified alert</CardTitle></CardHeader><CardContent className="grid gap-5 md:grid-cols-2"><div className="space-y-4"><Field label="Incident type"><Input value={draft.incidentType} onChange={e=>setDraft({...draft,incidentType:e.target.value.toLowerCase()})} placeholder="fire, flood, attack…"/></Field><Field label="Incident summary"><Textarea value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})}/></Field><Field label="Location"><Input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></Field><Field label="Emergency instructions"><Textarea value={draft.instructions} onChange={e=>setDraft({...draft,instructions:e.target.value})}/></Field></div><div className="space-y-5"><Field label="Threat level"><Select value={draft.threatLevel} onValueChange={v=>setDraft({...draft,threatLevel:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["low","medium","high","critical"].map(v=><SelectItem key={v} value={v}>{v.toUpperCase()}</SelectItem>)}</SelectContent></Select></Field><ChoiceList label="Delivery channels" items={(["sms","whatsapp"] as AlertChannel[]).map(c=>({id:c,name:c.toUpperCase()}))} selected={channels} toggle={v=>toggle(v as AlertChannel,channels,setChannels)}/><ChoiceList label="Target watch groups" items={admin.groups.map(g=>({id:g.id,name:`${g.name} (${g.memberCount})`}))} selected={groupIds} toggle={v=>toggle(v,groupIds,setGroupIds)}/><ChoiceList label="Specific emergency contacts (optional)" items={admin.contacts.filter(c=>c.active).map(c=>({id:c.id,name:`${c.name} — ${c.category.replace("_"," ")}`}))} selected={contactIds} toggle={v=>toggle(v,contactIds,setContactIds)}/><p className="text-sm text-muted-foreground">Estimated audience: {recipients}. If no contacts are selected, contacts matching the incident type are included automatically.</p><Button className="w-full" variant="destructive" disabled={sending} onClick={send}>{sending?"Sending…":t.sendAlert}</Button></div></CardContent></Card></TabsContent>
      <TabsContent value="groups" className="space-y-4"><Card><CardHeader><CardTitle>Create watch group</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-5"><Input placeholder="Group name" value={group.name} onChange={e=>setGroup({...group,name:e.target.value})}/><Input placeholder="Community" value={group.community} onChange={e=>setGroup({...group,community:e.target.value})}/><Input placeholder="Ward" value={group.ward} onChange={e=>setGroup({...group,ward:e.target.value})}/><Input placeholder="Coordinator" value={group.leader} onChange={e=>setGroup({...group,leader:e.target.value})}/><Button onClick={()=>run(()=>admin.createGroup(group),"Group created")} disabled={!group.name||!group.community}>Create</Button></CardContent></Card><Card><CardHeader><CardTitle>Add group member</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-5"><Select value={member.groupId} onValueChange={v=>setMember({...member,groupId:v})}><SelectTrigger><SelectValue placeholder="Group"/></SelectTrigger><SelectContent>{admin.groups.map(g=><SelectItem key={g.id} value={g.id}>{g.name}</SelectItem>)}</SelectContent></Select><Input placeholder="Member name" value={member.name} onChange={e=>setMember({...member,name:e.target.value})}/><Input placeholder="SMS phone (+234…)" value={member.phone} onChange={e=>setMember({...member,phone:e.target.value})}/><Input placeholder="WhatsApp (+234…)" value={member.whatsapp} onChange={e=>setMember({...member,whatsapp:e.target.value})}/><Button onClick={()=>run(()=>admin.addMember(member.groupId,member),"Member added")} disabled={!member.groupId||!member.name||!member.phone}>Add</Button></CardContent></Card><div className="grid gap-3 md:grid-cols-2">{admin.groups.map(g=><Card key={g.id}><CardHeader className="flex-row items-start justify-between"><CardTitle className="text-base">{g.name}</CardTitle><Button size="icon" variant="ghost" onClick={()=>run(()=>admin.deleteGroup(g.id),"Group removed")}><Trash2 className="h-4 w-4"/></Button></CardHeader><CardContent className="text-sm"><p>{g.community} · {g.ward||"No ward"}</p><p>Coordinator: {g.leader}</p><p className="text-muted-foreground">{g.memberCount} registered members</p></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="contacts" className="space-y-4"><Card><CardHeader><CardTitle>Register emergency contact</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><Input placeholder="Contact name" value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/><Select value={contact.category} onValueChange={v=>setContact({...contact,category:v as ContactCategory})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["police","hospital","fire_service","community_leader","volunteer","other"].map(v=><SelectItem key={v} value={v}>{v.replace("_"," ")}</SelectItem>)}</SelectContent></Select><Input placeholder="SMS phone (+234…)" value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/><Input placeholder="WhatsApp (+234…)" value={contact.whatsapp} onChange={e=>setContact({...contact,whatsapp:e.target.value})}/><Input placeholder="Community (optional)" value={contact.community} onChange={e=>setContact({...contact,community:e.target.value})}/><Input placeholder="Incident types: fire,flood" value={contact.incidentTypes} onChange={e=>setContact({...contact,incidentTypes:e.target.value})}/><Input type="number" min={1} max={10} value={contact.authorityLevel} onChange={e=>setContact({...contact,authorityLevel:Number(e.target.value)})}/><Button onClick={()=>run(()=>admin.createContact(contact),"Contact registered")} disabled={!contact.name||!contact.phone}>Register</Button></CardContent></Card><div className="grid gap-3 md:grid-cols-3">{admin.contacts.map(c=><Card key={c.id}><CardContent className="p-5"><div className="flex justify-between"><div><p className="font-semibold">{c.name}</p><p className="text-sm capitalize text-muted-foreground">{c.category.replace("_"," ")}</p></div><Button size="icon" variant="ghost" onClick={()=>run(()=>admin.deleteContact(c.id),"Contact removed")}><Trash2 className="h-4 w-4"/></Button></div><p className="mt-2 font-mono text-sm">{c.phone}</p><label className="mt-3 flex items-center gap-2 text-sm"><Checkbox checked={c.active} onCheckedChange={v=>run(()=>admin.toggleContact(c.id,Boolean(v)),"Contact updated")}/>Active</label></CardContent></Card>)}</div></TabsContent>
    </Tabs>{admin.loading&&<p className="text-center text-sm text-muted-foreground">Loading alert directory…</p>}</div></main>;
}
function Stat({icon,value,label}:{icon:ReactNode;value:string|number;label:string}){return <Card><CardContent className="flex items-center gap-3 p-5">{icon}<div><p className="text-2xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>}
function Field({label,children}:{label:string;children:ReactNode}){return <div><Label>{label}</Label>{children}</div>}
function ChoiceList({label,items,selected,toggle}:{label:string;items:{id:string;name:string}[];selected:string[];toggle:(id:string)=>void}){return <fieldset><Label>{label}</Label>{items.length?items.map(i=><label key={i.id} className="mt-2 flex items-center gap-2 rounded border p-3"><Checkbox checked={selected.includes(i.id)} onCheckedChange={()=>toggle(i.id)}/><span>{i.name}</span></label>):<p className="mt-2 text-sm text-muted-foreground">None configured.</p>}</fieldset>}
