import type { LucideIcon } from "lucide-react";
import { Link } from "react-router-dom";
import {
  Activity,
  BellRing,
  Camera,
  Database,
  FileWarning,
  MapPinned,
  Megaphone,
  RadioTower,
  ScanFace,
  Settings,
  ShieldAlert,
  Users,
} from "lucide-react";

import { Header } from "@/components/dashboard/Header";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

type ModuleStatus = "Active" | "Development";

interface ModuleItem {
  title: string;
  description: string;
  path: string;
  icon: LucideIcon;
  status: ModuleStatus;
}

const modules: ModuleItem[] = [
  {
    title: "Community Dashboard",
    description:
      "View community incidents, emergency reports, response tracking, and live status updates.",
    path: "/community-dashboard",
    icon: Users,
    status: "Active",
  },
  
  {
    title: "Citizen Incident Reporting",
    description:
      "Allow community members to report attacks, kidnappings, fires, floods, accidents, medical emergencies, and other threats.",
    path: "/incident-report",
    icon: FileWarning,
    status: "Active",
  },
  {
    title: "Emergency Resource Map",
    description:
      "Find hospitals, police stations, shelters, fire services, emergency offices, and IDP camps.",
    path: "/resources",
    icon: MapPinned,
    status: "Active",
  },
  {
    title: "Camera Management",
    description:
      "Configure cameras, monitor live streams, manage recording sources, and review surveillance zones.",
    path: "/cameras",
    icon: Camera,
    status: "Active",
  },
  {
    title: "Detection Manager",
    description:
      "Manage AI detection rules, threat recognition, detection sensitivity, and automated monitoring settings.",
    path: "/detection",
    icon: ShieldAlert,
    status: "Active",
  },
  {
    title: "Sensor Management",
    description:
      "Configure connected sensors and monitor their current operating status across deployment locations.",
    path: "/sensors",
    icon: RadioTower,
    status: "Active",
  },
  {
    title: "Face Recognition",
    description:
      "Manage recognised faces, unknown detections, and facial identification records.",
    path: "/faces",
    icon: ScanFace,
    status: "Active",
  },
  {
    title: "Deployments",
    description:
      "Review system deployments, installation sites, active environments, and operational coverage.",
    path: "/deployments",
    icon: Database,
    status: "Active",
  },
  {
    title: "Administration",
    description:
      "Manage users, roles, integrations, webhooks, platform settings, audit logs, and system configuration.",
    path: "/admin",
    icon: Settings,
    status: "Active",
  },
  {
    title: "Notifications",
    description:
      "Review alerts and emergency communications generated by the AIJE platform.",
    path: "/notifications",
    icon: BellRing,
    status: "Development",
  },
];

export default function ControlPanel() {
  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main className="mx-auto max-w-[1600px] space-y-8 px-4 py-6 md:px-6">
        <section className="space-y-2">
          <div className="flex items-center gap-2 text-primary">
            <Activity className="h-4 w-4" aria-hidden="true" />
            <p className="text-sm font-medium uppercase tracking-[0.18em]">
              AIJE Operations
            </p>
          </div>

          <h1 className="text-3xl font-bold tracking-tight text-foreground">
            Control Panel
          </h1>

          <p className="max-w-3xl text-sm leading-6 text-muted-foreground md:text-base">
            Access and manage every operational module connected to the AIJE
            Community Shield platform.
          </p>
        </section>

        <section
          className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"
          aria-label="AIJE operational modules"
        >
          {modules.map((module) => {
            const Icon = module.icon;
            const isActive = module.status === "Active";

            return (
              <Card
                key={module.title}
                className="flex h-full flex-col border-border bg-card transition duration-200 hover:-translate-y-0.5 hover:shadow-lg"
              >
                <CardHeader className="space-y-4">
                  <div className="flex items-start justify-between gap-3">
                    <div className="rounded-xl bg-primary/10 p-3 text-primary">
                      <Icon className="h-6 w-6" aria-hidden="true" />
                    </div>

                    <span
                      className={
                        isActive
                          ? "rounded-full bg-green-500/10 px-2.5 py-1 text-xs font-medium text-green-600 dark:text-green-400"
                          : "rounded-full bg-amber-500/10 px-2.5 py-1 text-xs font-medium text-amber-600 dark:text-amber-400"
                      }
                    >
                      {module.status}
                    </span>
                  </div>

                  <CardTitle className="text-lg">{module.title}</CardTitle>
                </CardHeader>

                <CardContent className="flex flex-1 flex-col justify-between gap-5">
                  <p className="text-sm leading-6 text-muted-foreground">
                    {module.description}
                  </p>

                  {isActive ? (
                    <Button asChild className="w-full">
                      <Link to={module.path}>Open Module</Link>
                    </Button>
                  ) : (
                    <Button
                      type="button"
                      className="w-full"
                      disabled
                      aria-disabled="true"
                    >
                      Coming Soon
                    </Button>
                  )}
                </CardContent>
              </Card>
            );
          })}
        </section>
      </main>
    </div>
  );
}