import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
type Draft={incidentId?:string;incidentType:string;summary:string;location:string;threatLevel:string;instructions:string;occurredAt:string;channels:("sms"|"whatsapp")[];groupIds:string[];contactIds:string[];language:string;media?:{type:"image"|"map";url:string;caption?:string}[]};
const smsText=(d:Draft)=>`[AIJE ${d.threatLevel.toUpperCase()}] ${d.incidentType} — ${d.location}. ${new Date(d.occurredAt).toLocaleString("en-NG")}. ${d.instructions}`.slice(0,480);
const waText=(d:Draft)=>`*AIJE VERIFIED ALERT*\n${d.summary}\nLocation: ${d.location}\nThreat: ${d.threatLevel.toUpperCase()}\nTime: ${new Date(d.occurredAt).toLocaleString("en-NG")}${d.media?.[0]?.url?`\nMedia: ${d.media[0].url}`:""}`;
async function deliver(channel:string,to:string,message:string){
  if(channel==="sms"&&Deno.env.get("SMS_PROVIDER")==="termii"){const r=await fetch("https://api.ng.termii.com/api/sms/send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({api_key:Deno.env.get("TERMII_API_KEY"),to,from:Deno.env.get("TERMII_SENDER_ID")??"AIJE",sms:message,type:"plain",channel:"generic"})});if(!r.ok)throw new Error(`Termii ${r.status}`);return {provider:"termii",id:(await r.json()).message_id}}
  if((channel==="sms"&&Deno.env.get("SMS_PROVIDER")==="twilio")||channel==="whatsapp"){const sid=Deno.env.get("TWILIO_ACCOUNT_SID")!,token=Deno.env.get("TWILIO_AUTH_TOKEN")!,from=channel==="whatsapp"?Deno.env.get("TWILIO_WHATSAPP_FROM")!:Deno.env.get("TWILIO_SMS_FROM")!;const body=new URLSearchParams({To:channel==="whatsapp"?`whatsapp:${to}`:to,From:from,Body:message});const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:"POST",headers:{Authorization:`Basic ${btoa(`${sid}:${token}`)}`,"content-type":"application/x-www-form-urlencoded"},body});if(!r.ok)throw new Error(`Twilio ${r.status}`);return {provider:"twilio",id:(await r.json()).sid}}
  throw new Error(`No ${channel} provider configured`);
}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const auth=req.headers.get("Authorization")??"";const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{global:{headers:{Authorization:auth}}});const {data:{user}}=await db.auth.getUser(auth.replace("Bearer ",""));if(!user)throw new Error("Unauthorized");const d=await req.json() as Draft;if(!d.incidentType||!d.summary||!d.location||!d.channels?.length||(!d.groupIds?.length&&!d.contactIds?.length))throw new Error("Invalid alert");const intervals=d.groupIds.length?await db.from("community_watch_groups").select("escalation_minutes").in("id",d.groupIds):{data:[]};const minutes=Math.min(...(intervals.data??[]).map((g:any)=>g.escalation_minutes),15);const {data:a,error}=await db.from("community_alerts").insert({owner_id:user.id,incident_id:d.incidentId,incident_type:d.incidentType,summary:d.summary,location:d.location,threat_level:d.threatLevel,instructions:d.instructions,occurred_at:d.occurredAt,language:d.language,next_escalation_at:new Date(Date.now()+minutes*60000).toISOString()}).select().single();if(error)throw error;if(d.groupIds.length)await db.from("community_alert_targets").insert(d.groupIds.map(group_id=>({alert_id:a.id,group_id})));const {data:members}=d.groupIds.length?await db.from("community_group_members").select("phone,whatsapp_target,sms_enabled,whatsapp_enabled").in("group_id",d.groupIds):{data:[]};let contactQuery=db.from("emergency_contacts").select("phone,whatsapp_target").eq("owner_id",user.id).eq("active",true);if(d.contactIds?.length)contactQuery=contactQuery.in("id",d.contactIds);else contactQuery=contactQuery.or(`incident_types.cs.{${d.incidentType}},incident_types.eq.{}`);const {data:contacts}=await contactQuery;const recipients=[...(members??[]),...(contacts??[]).map(c=>({...c,sms_enabled:true,whatsapp_enabled:Boolean(c.whatsapp_target)}))];let delivered=0,failed=0;for(const m of recipients)for(const ch of d.channels){const to=ch==="sms"&&m.sms_enabled?m.phone:ch==="whatsapp"&&m.whatsapp_enabled?m.whatsapp_target:null;if(!to)continue;try{const out=await deliver(ch,to,ch==="sms"?smsText(d):waText(d));await db.from("alert_deliveries").insert({alert_id:a.id,channel:ch,recipient:to,provider:out.provider,provider_message_id:out.id,status:"sent",attempts:1});delivered++}catch(e){await db.from("alert_deliveries").insert({alert_id:a.id,channel:ch,recipient:to,provider:"configured",status:"failed",error:String(e),attempts:1});failed++}}return new Response(JSON.stringify({alertId:a.id,queued:0,delivered,failed}),{headers:{...cors,"content-type":"application/json"}})}catch(e){return new Response(JSON.stringify({error:String(e)}),{status:400,headers:{...cors,"content-type":"application/json"}})}});
